const express = require("express");
const params = require("../routes/param");
const leagues = require("../routes/league");
const seasons = require("../routes/seasons");
const betdomains = require("../routes/betdomains");
const userdomains = require("../routes/userdomains");
const communities = require("../routes/communities");
const leaguesgenres = require("../routes/leaguesgenres");
const users = require("../routes/users");
const bets = require("../routes/bets");
const gameweeks = require("../routes/gameweeks");
const titles = require("../routes/titles");
const betdetails = require("../routes/betdetails");
const calendar = require("../routes/calendar");
const auth = require("../routes/auth");
const home = require("../routes/home");
const points = require("../routes/points");
const ranks = require("../routes/ranks");
const countries = require("../routes/countries");
const confirmmail = require("../routes/confirmmail");
const sendverificationmail = require("../routes/sendverificationmail");
const emailresetverification = require("../routes/emailresetverification");
const resetpassword = require("../routes/resetpassword");
const error = require("../middleware/error");

module.exports = function (app) {
  app.use(express.json());
  app.use(express.urlencoded({ extended: true }));
  app.use(express.static("public"));
  app.use("/api/leagues", leagues);
  app.use("/api/seasons", seasons);
  app.use("/api/betdomains", betdomains);
  app.use("/api/userdomains", userdomains);
  app.use("/api/communities", communities);
  app.use("/api/leaguesgenres", leaguesgenres);
  app.use("/api/confirmation", confirmmail);
  app.use("/api/loginconfirmation", sendverificationmail);
  app.use("/api/checkemail", emailresetverification);
  app.use("/api/resetpassword", resetpassword);
  app.use("/api/params", params);
  app.use("/api/calendar", calendar);
  app.use("/api/gameweeks", gameweeks);
  app.use("/api/ranks", ranks);
  app.use("/api/bets", bets);
  app.use("/api/titles", titles);
  app.use("/api/betdetails", betdetails);
  app.use("/api/auth", auth);
  app.use("/api/users", users);
  app.use("/api/points", points);
  app.use("/api/countries", countries);
  app.use("/", home);
  app.use(error);
};
